custom_guidelines:
  general:
    - name: ""
      path: ""
exclude_draft_pr: false
exclude_files: '*.xml,*.json,*.properties,.gitignore,*.yml,*.md'
include_source_branches: "*,[a-z"
include_target_branches: "*,[a-z"
linters_feedback: true
post_changelist: true
post_description: true
secret_scanner_feedback: true
suggestion_mode: comprehensive
labels_excluded: "[^bito\W]+"
