suggestion_mode: comprehensive
post_description: true
post_changelist: true
include_source_branches: feature/**,bugfix/**
include_target_branches: main,develop
exclude_files: docs/**,README.md
exclude_draft_pr: true
secret_scanner_feedback: true
linters_feedback: true
dependency-check-enabled: true
jira_project_keys: PROJ
custom_guidelines:
  general:
    - name: "Global Checks"
      path: "/guidelines/global_checks.txt"
  per_language:
    java:
      name: "Java Coding Standards"
      path: "/guidelines/java.txt"
