suggestion_mode: comprehensive
post_description: value
post_changelist: false
include_source_branches: feature/**,bugfix/**
include_target_branches: main,develop
exclude_files: docs/**,README.md
exclude_draft_pr: true
secret_scanner_feedback: true
linters_feedback: true
dependency-check-enabled: true
