custom_guidelines:
  general:
    - name: ""
      path: ""
  per_language:
    java:
      name: ""
      path: ""
exclude_draft_pr: false
exclude_files: '*.xml,*.json,*.properties,.gitignore,*.yml,*.md'
include_source_branches: "*"
include_target_branches: "*"
linters_feedback: true
post_changelist: true
post_description: true
secret_scanner_feedback: true
suggestion_mode: comprehensive
